### ISSUE TITLE
Error when extracting gallery_images.cy

### ISSUE THREAD

**Issue by WiseMatthack** [Muzi-Chan/DDLC-Plus-Assets-Extractor#1]
Here's the error:
```Traceback (most recent call last):
  File "D:\matth\Documents\DDLC-Plus-Assets-Extractor-main\ddlcplus_decryptor.py", line 235, in <module>
    payload(path)
  File "D:\matth\Documents\DDLC-Plus-Assets-Extractor-main\ddlcplus_decryptor.py", line 215, in payload
    decryptfile(str(cyfile), str(path))
  File "D:\matth\Documents\DDLC-Plus-Assets-Extractor-main\ddlcplus_decryptor.py", line 39, in decryptfile
    xor = list(a ^ b for a, b in zip(f.read()[current_startoffset : endofpart], cycle(b'\x28')))
MemoryError```

**Comment by Muzi-Chan** [comment]
This error means you don't have enough RAM
the solution could be to change the number line 25/31/35/38/40 by something lower (it need be the same on each line), you can try 104857600 (100MB), maybe it'll works.

If too much people have this problem, I'll make this change global, and not a cheap hack to do.

**Comment by WiseMatthack** [comment]
This fixed my issue. Thank you very much!
